[config]
default_to_workspace = false

# --- test ---
[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.create-shape-json]
description = "Creates shape jsons for test"
script = [
	"cd resources/shape",
	"cargo run -p monstertruck-modeling --example bottle",
	"cargo run -p monstertruck-modeling --example cube",
	"cargo run -p monstertruck-modeling --example cylinder",
	"cargo run -p monstertruck-modeling --example punched-cube",
	"cargo run -p monstertruck-modeling --example torus-punched-cube",
	"cargo run -p monstertruck-modeling --example cube-in-cube",
	"cargo run -p monstertruck-modeling --example torus",
	"cargo run -p monstertruck-modeling --example sphere",
	"cargo run -p monstertruck-modeling --example torus -- 500 100 large-torus.json",
	"cargo run -p monstertruck-solid --example punched-cube-shapeops",
]

[tasks.cpu-test]
description = "Tests using only CPU"
command = "cargo"
args = [
	"test",
	"-p", "monstertruck-core",
	"-p", "monstertruck-traits",
	"-p", "monstertruck-geometry",
	"-p", "monstertruck-topology",
	"-p", "monstertruck-mesh",
	"-p", "monstertruck-meshing",
	"-p", "monstertruck-modeling",
	"-p", "monstertruck-solid",
	"-p", "monstertruck-step",
	"--features", "derive",
	"--features", "polynomial",
	"--", "--nocapture",
]

[tasks.cpu-nightly-test]
description = "Tests using only CPU"
command = "rustup"
args = [
	"run",
	"nightly",
	"cargo",
	"test",
	"-p", "monstertruck-core",
	"-p", "monstertruck-traits",
	"-p", "monstertruck-geometry",
	"-p", "monstertruck-topology",
	"-p", "monstertruck-mesh",
	"-p", "monstertruck-meshing",
	"-p", "monstertruck-modeling",
	"-p", "monstertruck-solid",
	"-p", "monstertruck-step",
	"--features", "derive",
	"--features", "polynomial",
	"--", "--nocapture",
]

[tasks.gpu-test]
description = "Tests using GPU"
command = "cargo"
args = [
	"test",
	"-p", "monstertruck-gpu",
	"-p", "monstertruck-render",
	"--", "--nocapture", "--test-threads=1",
]

[tasks.collect-gpu-artifacts]
description = "Collects artifacts for gpu tests"
script_runner = "@shell"
script = [
	"mkdir images",
	"mv monstertruck-gpu/output images/platform",
	"mv monstertruck-render/output images/rendimpl",
]

[tasks.ci-cpu-test]
dependencies = ["clean", "cpu-test"]

[tasks.ci-cpu-nightly-test]
dependencies = ["clean", "cpu-nightly-test"]

[tasks.ci-gpu-test]
dependencies = ["clean", "gpu-test", "collect-gpu-artifacts"]

[tasks.wasm-build]
description = "Build to wasm-target"
env = { "RUSTFLAGS" = "--cfg=web_sys_unstable_apis --cfg=getrandom_backend=\"wasm_js\"" }
command = "cargo"
args = ["build", "--target=wasm32-unknown-unknown"]

[tasks.webgl-build]
description = "Build to wasm-target with webgl feature"
env = { "RUSTFLAGS" = "--cfg=web_sys_unstable_apis --cfg=getrandom_backend=\"wasm_js\"" }
command = "cargo"
args = [
	"build",
	"--target=wasm32-unknown-unknown",
	"--features", "webgl"
]

[tasks.build-wgpu-examples]
description = "Build wasms"
env = { "RUSTFLAGS" = "--cfg=web_sys_unstable_apis --cfg=getrandom_backend=\"wasm_js\"" }
command = "cargo"
args = ["run", "--bin", "example-pages-generator"]

[tasks.js-test]
description = "test for js"
env = { "RUSTFLAGS" = "--cfg=getrandom_backend=\"wasm_js\"" }
script = [
	"cd monstertruck-wasm",
	"wasm-pack build --target web",
	"deno test -A tests/",
]

[tasks.adhoc-viewer]
description = "build adhoc viewer"
env = { "RUSTFLAGS" = "--cfg=getrandom_backend=\"wasm_js\"" }
script_runner = "@shell"
script = [
	"cd monstertruck-wasm",
	"wasm-pack build --target web",
	"cp examples/index.html pkg/",
	"cp examples/bootstrap.js pkg/",
	"cp examples/script.js pkg/",
]

[tasks.wasm-test]
dependencies = ["wasm-build", "webgl-build", "js-test"]

[tasks.page-build]
dependencies = ["adhoc-viewer", "build-wgpu-examples"]
