use std::fmt::Debug;

/// vector
#[derive(Clone, PartialEq, Debug, Default)]
pub struct Vector<T>(T);

/// 2-dim vector
///
/// The cross product `^` returns the signed area of the parallelogram streched by the two vectors.
/// ```
/// # use truck_geometry::*;
/// assert_eq!(vector_new!(2, 3) ^ vector_new!(4, 7), 2);
/// ```
pub type Vector2 = Vector<[f64; 2]>;
/// 3-dim vector
///
/// The cross product is represented by the operator `^`.
/// ```
/// # use truck_geometry::*;
/// assert_eq!(vector_new!(1, 2, 3) ^ vector_new!(2, 4, 7), vector_new!(2, -1, 0));
/// ```
pub type Vector3 = Vector<[f64; 3]>;
/// 4-dim vector
///
/// The 3 dimensional homogeneous vector is generated by `Vector4::new3()`.
/// ```
/// # use truck_geometry::*;
/// assert_eq!(Vector4::new3(1, 2, 3), vector_new!(1, 2, 3, 1));
/// ```
pub type Vector4 = Vector<[f64; 4]>;

/// square matrix
#[derive(Clone, PartialEq, Debug, Default)]
pub struct Matrix<T, M>(M, std::marker::PhantomData<fn() -> T>);
/// 2x2 matrix
pub type Matrix2 = Matrix<[f64; 2], [Vector2; 2]>;
/// 3x3 matrix
pub type Matrix3 = Matrix<[f64; 3], [Vector3; 3]>;
/// 4x4 matrix
pub type Matrix4 = Matrix<[f64; 4], [Vector4; 4]>;

/// Abstraction of the arrays which is the entity of `Vector` or `Matrix`.
pub trait EntityArray<T>:
    Sized + Clone + PartialEq + AsRef<[T]> + AsMut<[T]> + Debug + Default {
    const ORIGIN: Self;
}

/// knot vector
#[derive(Clone, PartialEq, Debug)]
pub struct KnotVec(Vec<f64>);

/// Defines a tolerance in the whole package
pub trait Tolerance: Sized + Debug {
    /// general tolerance
    const TOLERANCE: f64 = 1.0e-7;

    /// general tolerance of square order
    const TOLERANCE2: f64 = Self::TOLERANCE * Self::TOLERANCE;

    /// The "distance" is less than EPSILON.
    fn near(&self, other: &Self) -> bool;

    /// The "distance" is less than EPSILON2.
    fn near2(&self, other: &Self) -> bool;

    /// assert if `one` is not near `other`.
    fn assert_near(one: &Self, other: &Self) {
        assert!(
            one.near(other),
            "not near two values.\nvalue0: {:?}\nvalue1: {:?}",
            one,
            other
        );
    }

    /// assertion if `one` is not near `other` in square order.
    fn assert_near2(one: &Self, other: &Self) {
        assert!(
            one.near2(other),
            "not near two values in square order.\nvalue0: {:?}\nvalue1: {:?}",
            one,
            other
        );
    }
}

/// The structs defined the origin. `f64`, `Vector`, and so on.
pub trait Origin: Tolerance {
    /// origin point
    const ORIGIN: Self;

    /// near origin
    #[inline(always)]
    fn so_small(&self) -> bool { self.near(&Self::ORIGIN) }

    /// near origin in square order
    #[inline(always)]
    fn so_small2(&self) -> bool { self.near2(&Self::ORIGIN) }
}

/// 4-dimensional B-spline curve
/// # Examples
/// ```
/// use truck_geometry::*;
/// const N : usize = 100; // sample size in test
///
/// // the knot vector
/// let knot_vec = KnotVec::from(vec![0.0, 0.0, 0.0, 0.25, 0.25, 0.5, 0.5, 0.75, 0.75, 1.0, 1.0, 1.0]);
///
/// // sign up the control points in the vector of all points
/// let control_points = vec![ // the vector of the indices of control points
///     vector_new!(0.0, -2.0, 0.0, 2.0),
///     vector_new!(1.0, -1.0, 0.0, 1.0),
///     vector_new!(1.0, 0.0, 0.0, 1.0),
///     vector_new!(1.0, 1.0, 0.0, 1.0),
///     vector_new!(0.0, 2.0, 0.0, 2.0),
///     vector_new!(-1.0, 1.0, 0.0, 1.0),
///     vector_new!(-1.0, 0.0, 0.0, 1.0),
///     vector_new!(-1.0, -1.0, 0.0, 1.0),
///     vector_new!(0.0, -2.0, 0.0, 2.0),
/// ];
///
/// // cunstruct the B-spline curve
/// let bspline = BSplineCurve::new(knot_vec, control_points);
///
/// // This B-spline curve is a nurbs representation of the unit circle.
/// for i in 0..N {
///     let t = 1.0 / (N as f64) * (i as f64);
///     let v = bspline.subs(t); // We can use the instances as a function.
///     let c = (v[0] / v[3]).powi(2) + (v[1] / v[3]).powi(2);
///     f64::assert_near2(&c, &1.0);
/// }
/// ```
#[derive(Clone, PartialEq, Debug)]
pub struct BSplineCurve<T> {
    knot_vec: KnotVec,              // the knot vector
    control_points: Vec<Vector<T>>, // the indices of control points
}

/// 4-dimensional B-spline surface
/// # Examples
/// ```
/// use truck_geometry::*;
/// const N : usize = 100; // sample size in test
///
/// // the knot vectors
/// let knot_vec0 = KnotVec::from(vec![0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0]);
/// let knot_vec1 = KnotVec::from(vec![0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0]);
/// let knot_vecs = (knot_vec0, knot_vec1);
///
/// // the control points
/// let mut v = vec![vec![Vector4::zero(); 7]; 4];
/// v[0][0] = Vector4::new3(0.0, 0.0, 1.0);
/// v[0][1] = &v[0][0] / 3.0;
/// v[0][2] = v[0][1].clone();
/// v[0][3] = v[0][0].clone();
/// v[0][4] = v[0][1].clone();
/// v[0][5] = v[0][1].clone();
/// v[0][6] = v[0][0].clone();
/// v[1][0] = Vector4::new3(2.0, 0.0, 1.0) / 3.0;
/// v[1][1] = Vector4::new3(2.0, 4.0, 1.0) / 9.0;
/// v[1][2] = Vector4::new3(-2.0, 4.0, 1.0) / 9.0;
/// v[1][3] = Vector4::new3(-2.0, 0.0, 1.0) / 3.0;
/// v[1][4] = Vector4::new3(-2.0, -4.0, 1.0) / 9.0;
/// v[1][5] = Vector4::new3(2.0, -4.0, 1.0) / 9.0;
/// v[1][6] = Vector4::new3(2.0, 0.0, 1.0) / 3.0;
/// v[2][0] = Vector4::new3(2.0, 0.0, -1.0) / 3.0;
/// v[2][1] = Vector4::new3(2.0, 4.0, -1.0) / 9.0;
/// v[2][2] = Vector4::new3(-2.0, 4.0, -1.0) / 9.0;
/// v[2][3] = Vector4::new3(-2.0, 0.0, -1.0) / 3.0;
/// v[2][4] = Vector4::new3(-2.0, -4.0, -1.0) / 9.0;
/// v[2][5] = Vector4::new3(2.0, -4.0, -1.0) / 9.0;
/// v[2][6] = Vector4::new3(2.0, 0.0, -1.0) / 3.0;
/// v[3][0] = Vector4::new3(0.0, 0.0, -1.0);
/// v[3][1] = &v[3][0] / 3.0;
/// v[3][2] = v[3][1].clone();
/// v[3][3] = v[3][0].clone();
/// v[3][4] = v[3][1].clone();
/// v[3][5] = v[3][1].clone();
/// v[3][6] = v[3][0].clone();
///
/// // cunstruct the B-spline curve
/// let bspline = BSplineSurface::new(knot_vecs, v);
///
/// // This B-spline curve is a nurbs representation of the unit sphere.
/// for i in 0..N {
///     for j in 0..N {
///         let u = 1.0 / (N as f64) * (i as f64);
///         let v = 1.0 / (N as f64) * (j as f64);
///         let v = bspline.subs(u, v); // We can use the instances as a function.
///         let c = (v[0] / v[3]).powi(2) + (v[1] / v[3]).powi(2) + (v[2] / v[3]).powi(2);
///         f64::assert_near2(&c, &1.0);
///     }
/// }
/// ```
#[derive(Clone, PartialEq, Debug)]
pub struct BSplineSurface<T> {
    knot_vecs: (KnotVec, KnotVec),
    control_points: Vec<Vec<Vector<T>>>,
}

/// Error handler for [`Error`](./errors/enum.Error.html)
pub type Result<T> = std::result::Result<T, crate::errors::Error>;

#[macro_use]
pub mod vector;
pub mod bspcurve;
pub mod bspsurface;
pub mod errors;
pub mod knot_vec;
pub mod matrix;
pub mod tolerance;
